apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oup8d1ae4-python
  janus-idp.io/tekton: oup8d1ae4-python
  backstage.io/kubernetes-id: oup8d1ae4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oup8d1ae4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
